### ISSUE TITLE
How to know which hierarchical structure is being used?

### ISSUE THREAD

**Issue by sn3fru** [FlorianWilhelm/bhm-at-scale#4]
Is it possible to know how he is putting together the dendogram over time series? If so, would it be possible to explicitly pass this data on the outside?

**Comment by FlorianWilhelm** [comment]
Not sure I understand your question. The code is open source and the article explains the graphical model.

**Comment by FlorianWilhelm** [comment]
The hierarchy is explicitly defined in the source code, only the parameters on each level are then inferred. You can of course fix all parameters to certain values if you know them.
