### ISSUE TITLE
Kernel dies after inputting X array

### ISSUE THREAD

**Issue by Ajinkya-7895** [FlorianWilhelm/bhm-at-scale#8]
Hi,
I am trying the multi dimensional array using my own data , we have around 7 features and one target column, it is a time series data however when we call the check_model and guide function the kernel dies. Can you suggest some troubleshooting

**Comment by FlorianWilhelm** [comment]
That's really not much information to work with. If you are working on a commercial project, I am happy to help, but must charge a consulting fee on an hourly basis.

**Comment by FlorianWilhelm** [comment]
Closed as no further information provided.
